return {
  formatters_by_ft = {
    lua = { "stylua" },
    c = { "clang-format" },
    cpp = { "clang-format" },
    go = { "gofmt", "goimports" },
    ruby = { "rubocop" },
    php = { "php-cs-fixer" },
    blade = { "blade-formatter" },
    cs = { "csharpier" },
    zig = { "zig fmt" },
    odin = { "odin fmt" },
    c3 = { "c3fmt" },
    javascript = { "prettier" },
    javascriptreact = { "prettier" },
    typescript = { "prettier" },
    typescriptreact = { "prettier" },
    vue = { "prettier" },
    html = { "prettier" },
    css = { "prettier" },
    json = { "prettier" },
    yaml = { "prettier" },
    markdown = { "prettier" },
    graphql = { "prettier" },
    prisma = { "prisma-fmt" },
  },
  format_on_save = {
    timeout_ms = 500,
    lsp_fallback = true,
  },
}
