return {
  defaults = {
    file_ignore_patterns = {
      -- Ignore common build and dependency directories
      "node_modules",
      "vendor",
      "dist",
      "build",
      "target",
      "%.git",
      "%.cache",
      "%.next",
      "%.idea",
      "%.vscode",
      "%.DS_Store",
      
      -- Ignore specific file types
      "%.jpg",
      "%.jpeg",
      "%.png",
      "%.gif",
      "%.ico",
      "%.pdf",
      "%.zip",
      "%.tar.gz",
      "%.rar",
      "%.7z",
    },
    vimgrep_arguments = {
      "rg",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--smart-case",
      "--hidden",
      "--glob=!node_modules/*",
      "--glob=!vendor/*",
      "--glob=!dist/*",
      "--glob=!build/*",
      "--glob=!target/*",
      "--glob=!.git/*",
      "--glob=!.cache/*",
      "--glob=!.next/*",
      "--glob=!.idea/*",
      "--glob=!.vscode/*",
      "--glob=!.DS_Store",
    },
  },
} 